### ISSUE TITLE
Duplicated entries bug

### ISSUE THREAD

**Issue by lemourin** [ajshort/vscode-include-autocomplete#1]
>     // TODO Get the directories and extensions to search.
>     let dirs = this.dirs;
>     let exts = vscode.workspace.getConfiguration("include-autocomplete").get("extensions", []);
> 
>     // Add includes relative to the file.
>     if (delimiter === "<") {
>       dirs.push(dirname(document.uri.fsPath));
>     } else {
>       dirs.unshift(dirname(document.uri.fsPath));
>     }

Whenever one tries to trigger the completion, the entries found in the directory relative to the file are duplicated, commenting out the if statement fixes the issue. The more you trigger the completion the more duplicates you get.

**Comment by ajshort** [comment]
Ah yep - I'm guessing I need to clone the `dirs` var, as it's probably modifying the original `this.dirs`.
