### ISSUE TITLE
Add support to C files

### ISSUE THREAD

**Issue by trprado** [ajshort/vscode-include-autocomplete#4]
Would it be possible to add support for c files in the plug-in?

**Comment by Viterzgir** [comment]
In file extension.js in function activate(context)  add this:
context.subscriptions.push(vscode.languages.registerCompletionItemProvider("c", provider, "<", '"', "/", "\\"));
see the pic
![cheaders](https://user-images.githubusercontent.com/19819279/28251706-7c35c48c-6a72-11e7-92e2-f9df023163e1.png)
