### ISSUE TITLE
Can't complete with path, just complete single filename

### ISSUE THREAD

**Issue by Kurt-Shiwz** [ajshort/vscode-include-autocomplete#6]
Can't complete with path, just complete single filename
![image](https://user-images.githubusercontent.com/7554917/31388481-d399c8ae-ad93-11e7-8607-d8823d2275be.png)

**Comment by ajshort** [comment]
Are you referring to the green squiggly underline?

**Comment by Kurt-Shiwz** [comment]
Sorry, I find some mistake in c_cpp_properties.json. And i find if typed backspace will show nothing, can't complete the header.

**Comment by ajshort** [comment]
To trigger autocompletion after backspacing press Ctrl+Space.

**Comment by Kurt-Shiwz** [comment]
I can customized the hotkey? there has conflict in my env. @ajshort

**Comment by ajshort** [comment]
You can customise "Trigger Suggest" shortcut in the keyboard shortcuts editor.
